chartmuseum:
  env:
    open:
      DISABLE_API: false
      AUTH_ANONYMOUS_GET: true
    secret:
      BASIC_AUTH_USER: admin 
      BASIC_AUTH_PASS: admin 
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 80m
      memory: 64Mi
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - name: cm.10.0.2.15.nip.io
      path: /  

jenkins:
  Master:
    ImageTag: "2.176.4-alpine"
    Cpu: "500m"
    Memory: "500Mi"
    ServiceType: ClusterIP
    ServiceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    GlobalLibraries: true
    InstallPlugins:
    - durable-task:1.28
    - workflow-durable-task-step:2.28
    - blueocean:1.10.1
    - credentials:2.1.18
    - git:3.9.1
    - git-client:2.7.6
    - github:1.29.3
    - kubernetes:1.14.3
    - pipeline-utility-steps:2.2.0
    - pipeline-model-definition:1.3.4.1
    - thinBackup:1.9
    - workflow-aggregator:2.6
    - ssh-slaves:1.29.4
    - ssh-agent:1.17
    - jdk-tool:1.2
    - command-launcher:1.3
    - github-oauth:0.31
    - pegdown-formatter:1.3
    Ingress:
      Annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        ingress.kubernetes.io/ssl-redirect: "false"
        ingress.kubernetes.io/proxy-body-size: 50m
        ingress.kubernetes.io/proxy-request-buffering: "off"
      HostName: jenkins.10.0.2.15.nip.io 
    CustomConfigMap: true
    CredentialsXmlSecret: jenkins-credentials
    SecretsFilesSecret: jenkins-secrets
    DockerVM: false
  rbac:
    install: true
go-demo-5:
  ingress:
    host: go-demo-5.10.0.2.15.nip.io
